apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
type: Opaque
data:
  mongo-user: {{default "" .Values.secret.data.user | quote }}
  mongo-password: {{default "" .Values.secret.data.password | quote }}